/**
 * FAQ content. The six homepage questions are ported verbatim from the live
 * site's FAQPage JSON-LD so the structured data stays at parity.
 */

export type Faq = { q: string; a: string };

export const HOME_FAQS: Faq[] = [
  {
    q: "What is ojao?",
    a: "ojao is a cloud-based digital patient flow and queue management platform for hospitals, clinics, diagnostic labs, and radiology centers. It replaces paper tokens and physical waiting lines with a live, trackable digital queue.",
  },
  {
    q: "Do patients need to download an app to use ojao?",
    a: "No. Patients can track their queue position from a mobile browser via SMS or QR code link. The ojao app is available for those who want push notifications, but it isn't required to use the core queueing experience.",
  },
  {
    q: "Can ojao handle both walk-in and scheduled patients?",
    a: "Yes. Walk-ins and pre-booked appointments are merged into a single ordered queue per doctor or department, so front-desk staff don't need to manage two separate systems.",
  },
  {
    q: "Does ojao require new hardware to get started?",
    a: "No dedicated kiosk hardware is required. ojao is designed to run on the tablets, desktops, and phones a clinic or hospital already has at the front desk.",
  },
  {
    q: "Can ojao support multiple departments in one hospital?",
    a: "Yes. Each department or doctor gets its own queue, and administrators get a single live dashboard across all of them instead of checking department by department.",
  },
  {
    q: "How is patient data handled?",
    a: "ojao only stores the minimum information needed to manage queue position and notifications — not clinical records. See our security page for details on encryption, access control, and data retention.",
  },
];

export const PRICING_FAQS: Faq[] = [
  {
    q: "How is ojao priced?",
    a: "ojao is priced on a custom enterprise basis depending on the number of departments, doctors, and locations involved. Request a demo to get a quote scoped to your facility.",
  },
  {
    q: "Is there a pilot option before a full rollout?",
    a: "Yes — we recommend piloting in a single department first so your team can evaluate the fit before a facility-wide rollout.",
  },
  {
    q: "Does pricing include onboarding and staff training?",
    a: "Onboarding scope is discussed as part of the enterprise quote — reach out via the demo request form and we'll walk through what's included for your facility size.",
  },
];

export const SECURITY_FAQS: Faq[] = [
  {
    q: "Does ojao store clinical or medical records?",
    a: "No. ojao only stores the information needed to manage a patient's position in a queue and notify them — not diagnoses, prescriptions, lab results, or other clinical data. Clinical records stay in your existing EMR/HIS.",
  },
  {
    q: "Who owns the data generated by our hospital on ojao?",
    a: "Your hospital or clinic owns the queue and operational data it generates. We don't sell, share, or repurpose it for any other use.",
  },
  {
    q: "Is ojao compliant with India's Digital Personal Data Protection Act, 2023?",
    a: "ojao's data handling — minimal collection, purpose limitation, and a clear deletion path — is built around the principles set out in the DPDP Act, 2023. We're happy to walk hospital compliance teams through our specific data flows on request.",
  },
  {
    q: "Can we request our data be deleted?",
    a: "Yes. Hospitals can request deletion of their historical queue and session data for their facility at any time; ask your account contact for the process.",
  },
  {
    q: "How is access to the admin dashboard controlled?",
    a: "Access is role-based — receptionists, doctors, department admins, and hospital administrators each see only what's relevant to their role, and every account is individually attributable rather than shared.",
  },
];
